### PR TITLE
#183 state remastering

### PR DESCRIPTION
**Pull request by kramlex**

### CODE REVIEW

**Review by Alex009 — APPROVED** [review]

**Comment by Alex009** [comment]
@kramlex  detekt fixes required. check CI runs

**Comment by kramlex** [comment]
@Alex009 I don't understand. With the use of `TestRule` in the `commonMain` source set, the build falls on **ubuntu** test, and without it it also falls. What to do?

**Review by Alex009 — CHANGES_REQUESTED** [review]
tests fix required

**Comment by kramlex** [comment]
work has resumed in a new [merge request](https://github.com/icerockdev/moko-mvvm/pull/215)

**Pull request closed without merging**
